In [16]:
!pip install pydot graphviz

In [17]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import load_model

In [18]:
with open('Text.txt','r',encoding='latin-1') as f:
  data=f.readlines()

In [19]:
corpus=data[:5000]

In [20]:
text_data=[sentence.replace('\n',' ') for sentence in corpus]

In [21]:
text_data = ' '.join(corpus)

In [22]:
text_data[200:2000]

'" \n "Do the dead frighten you?" Ser Waymar Royce asked with just the hint of a smile. \n Gared did not rise to the bait. He was an old man, past fifty, and he had seen the lordlings come and go. \n "Dead is dead," he said. "We have no business with the dead." \n "Are they dead?" Royce asked softly. "What proof have we?" \n "Will saw them," Gared said. "If he says they are dead, that\'s proof enough for me." \n Will had known they would drag him into the quarrel sooner or later. He wished it had been later rather \n than sooner. "My mother told me that dead men sing no songs," he put in. \n "My wet nurse said the same thing, Will," Royce replied. "Never believe anything you hear at a woman\'s \n tit. There are things to be learned even from the dead." His voice echoed, too loud in the twilit forest. \n Page 1\n \n "We have a long ride before us," Gared pointed out. "Eight days, maybe nine. And night is falling." \n Ser Waymar Royce glanced at the sky with disinterest. "It does that ev

In [23]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text_data])

In [24]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'a': 3,
 'to': 4,
 'he': 5,
 'of': 6,
 'his': 7,
 'was': 8,
 'her': 9,
 'in': 10,
 'it': 11,
 'had': 12,
 'you': 13,
 'she': 14,
 'him': 15,
 'i': 16,
 'that': 17,
 'with': 18,
 'said': 19,
 'as': 20,
 'at': 21,
 'not': 22,
 'on': 23,
 'for': 24,
 'they': 25,
 'is': 26,
 'but': 27,
 'were': 28,
 'jon': 29,
 'no': 30,
 'from': 31,
 'have': 32,
 'my': 33,
 'all': 34,
 'them': 35,
 'ned': 36,
 'be': 37,
 'will': 38,
 'would': 39,
 'when': 40,
 'your': 41,
 'there': 42,
 'up': 43,
 'what': 44,
 'so': 45,
 'are': 46,
 'bran': 47,
 'one': 48,
 'me': 49,
 'out': 50,
 'been': 51,
 'man': 52,
 'if': 53,
 'could': 54,
 'like': 55,
 'this': 56,
 'eyes': 57,
 'looked': 58,
 'back': 59,
 'lord': 60,
 'then': 61,
 'their': 62,
 'king': 63,
 'ser': 64,
 'did': 65,
 'arya': 66,
 'catelyn': 67,
 'do': 68,
 'hand': 69,
 'we': 70,
 'down': 71,
 'than': 72,
 'by': 73,
 'page': 74,
 'never': 75,
 'see': 76,
 'into': 77,
 'told': 78,
 'robert': 79,
 'sansa': 80,
 'tyrion': 81,
 'now':

In [25]:
len(tokenizer.word_index)

6276

In [26]:
sent='He is very happy man.'
tokenized_sent=tokenizer.texts_to_sequences([sent])
tokenized_sent

[[5, 26, 222, 3069, 52]]

In [27]:
input_seq=[]
for sent in text_data.split('\n'):
  tokenized_sent=tokenizer.texts_to_sequences([sent])[0]
  for i in range(1,len(tokenized_sent)):
    input_seq.append(tokenized_sent[:i+1])

for i in input_seq:
  print(i)


Streaming output truncated to the last 5000 lines.
[593, 575, 15, 5, 121, 1, 324, 594, 164, 21, 3, 108, 73, 1, 108, 5, 1621, 77, 1, 2473, 6]
[593, 575, 15, 5, 121, 1, 324, 594, 164, 21, 3, 108, 73, 1, 108, 5, 1621, 77, 1, 2473, 6, 1]
[60, 565]
[60, 565, 7]
[60, 565, 7, 1001]
[60, 565, 7, 1001, 28]
[60, 565, 7, 1001, 28, 1688]
[60, 565, 7, 1001, 28, 1688, 2]
[60, 565, 7, 1001, 28, 1688, 2, 29]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8, 823]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8, 823, 781]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8, 823, 781, 2]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8, 823, 781, 2, 2007]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8, 823, 781, 2, 2007, 47]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8, 823, 781, 2, 2007, 47, 5]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8, 823, 781, 2, 2007, 47, 5, 19]
[60, 565, 7, 1001, 28, 1688, 2, 29, 8, 823, 781, 2, 2007, 47, 5, 19, 44]
[336, 11]
[336, 11, 188]
[336, 11, 188, 122]
[336, 11, 188, 122, 47]
[6013, 514]
[6013, 514, 

In [28]:
len(input_seq)

67179

In [29]:
max_len=max([len(sent) for sent in input_seq])

In [30]:
max_len

24

In [31]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [32]:
padded_input_seq=pad_sequences(input_seq,maxlen=max_len,padding='pre',truncating='pre')

In [33]:
padded_input_seq[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3, 996], dtype=int32)

In [34]:
X = padded_input_seq[:, :-1]
y = padded_input_seq[:, -1]

In [35]:
X[:5], X.shape

(array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   3],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   3, 996],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   3, 996,   6],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0, 776],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 776,  48]], dtype=int32),
 (67179, 23))

In [36]:
list(y)

[996,
 6,
 1632,
 48,
 6,
 3,
 1223,
 6,
 334,
 2,
 256,
 2477,
 841,
 841,
 1633,
 207,
 1095,
 59,
 335,
 1634,
 20,
 1,
 842,
 242,
 4,
 914,
 246,
 105,
 35,
 1,
 1635,
 46,
 1,
 177,
 1224,
 13,
 64,
 411,
 412,
 145,
 18,
 163,
 1,
 1636,
 6,
 3,
 247,
 65,
 22,
 997,
 4,
 1,
 3444,
 5,
 8,
 83,
 103,
 52,
 305,
 1948,
 2,
 5,
 12,
 216,
 1,
 3445,
 124,
 2,
 118,
 26,
 177,
 5,
 19,
 70,
 32,
 30,
 915,
 18,
 1,
 177,
 25,
 177,
 412,
 145,
 667,
 44,
 843,
 32,
 70,
 137,
 35,
 335,
 19,
 53,
 5,
 491,
 25,
 46,
 177,
 429,
 843,
 199,
 24,
 49,
 12,
 561,
 25,
 39,
 3446,
 15,
 77,
 1,
 3447,
 668,
 95,
 777,
 5,
 1372,
 11,
 12,
 51,
 777,
 630,
 668,
 33,
 248,
 78,
 49,
 17,
 177,
 92,
 1637,
 30,
 1225,
 5,
 185,
 10,
 669,
 844,
 19,
 1,
 413,
 297,
 38,
 412,
 325,
 75,
 670,
 631,
 13,
 257,
 21,
 3,
 1373,
 42,
 46,
 298,
 4,
 37,
 1096,
 107,
 31,
 1,
 177,
 7,
 126,
 916,
 102,
 1638,
 10,
 1,
 3449,
 562,
 1639,
 32,
 3,
 93,
 287,
 106,
 141,
 335,
 671,
 50,
 726,

In [37]:
y, y.shape

(array([ 996,    6, 1632, ...,   41,  317, 1608], dtype=int32), (67179,))

In [38]:
word2idx=tokenizer.word_index
len_vocab=len(word2idx)
len_vocab

6276

In [39]:
y = y.reshape(-1,1)

In [40]:
y.shape

(67179, 1)

In [41]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(list(y),num_classes=len_vocab+1)

# With Trainable Embedding

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

# Creating the Model
model1 = Sequential()
model1.add(Embedding(len_vocab + 1, 30, input_length=max_len - 1))
model1.add(GRU(150, return_sequences=True))  # First GRU layer with return_sequences=True
model1.add(GRU(100))  # Second GRU layer without return_sequences (output the final hidden state)
model1.add(Dense(len_vocab + 1, activation='softmax'))

# Compiling the model
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Checking summary
model1.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru (GRU)                            │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru_1 (GRU)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [43]:
model1.fit(X,y,epochs=50)

Epoch 1/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 34s 10ms/step - accuracy: 0.0601 - loss: 6.9006
Epoch 2/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 38s 9ms/step - accuracy: 0.0746 - loss: 6.1529
Epoch 3/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 21s 9ms/step - accuracy: 0.0969 - loss: 5.7536
Epoch 4/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 19s 9ms/step - accuracy: 0.1184 - loss: 5.3796
Epoch 5/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 21s 9ms/step - accuracy: 0.1310 - loss: 5.0637
Epoch 6/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 21s 9ms/step - accuracy: 0.1466 - loss: 4.7980
Epoch 7/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 19s 9ms/step - accuracy: 0.1617 - loss: 4.5664
Epoch 8/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 22s 10ms/step - accuracy: 0.1757 - loss: 4.3495
Epoch 9/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 20s 10ms/step - accuracy: 0.1929 - loss: 4.1494
Epoch 10/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 20s 9ms/step - accuracy: 0.2163 - loss: 3.9703
Epoch 11/50
2100/2100 ━━━━━━━━━━━━━━━━━━━━ 20s 10ms/step - accuracy: 0.2352 - loss: 3.8071
Epoch 12/50
210

In [45]:
# Predictor

import time
text = "Arya"

for i in range(30):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=max_len-1, padding='pre')
  # predict
  pos = np.argmax(model1.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      # time.sleep(1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Arya was
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Arya was a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Arya was a child
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
Arya was a child i
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Arya was a child i must
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Arya was a child i must never
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
Arya was a child i must never be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Arya was a child i must never be too
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Arya was a child i must never be too kind
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Arya was a child i must never be too kind to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Arya was a child i must never be too kind to him
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
Arya was a child i must never be too kind to him for
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Arya was a child i must never be too kind to him for him
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
Arya was a child i must never be too kind 

In [46]:
model1.save('model1.keras')